# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test executor inputs

on:
  workflow_dispatch:
  pull_request:
    branches: [main, develop, develop-feijoa]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: eslint
        run: npm run eslint
      - name: run zkasm tests
        run: npm run test:zkasm
